name: Link checker

on:
  push:
    branches: [main, "repo-refresh-*"]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"  # Every Monday at 6am UTC

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Check links
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
        with:
          args: >
            --verbose
            --no-progress
            --exclude "localhost"
            --exclude "LINK_TBD"
            --exclude "aka.ms"
            --exclude "foundershub.startups.microsoft.com"
            '**/*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}